export const LOAD_TODOS = 'LOAD_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TOGGLE_ALL_TODO = 'TOGGLE_ALL_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const BACKEND_ACTION_STARTED = 'BACKEND_ACTION_STARTED';
export const BACKEND_ACTION_FINISHED = 'BACKEND_ACTION_FINISHED';
export const SET_CURRENT_FILTER = 'SET_CURRENT_FILTER';
